server:
  port: 8004

spring:
  application:
    name: order-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

jwt:
  secretkey: TheServerSecretKey

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8012/eureka/
    healthcheck:
      enabled: true
      
app:
  order:
    shipping:
      standard-charges: 20
