server:
  port: ${port:8004}

spring:
  application:
    name: order-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8012/eureka/}
    healthcheck:
      enabled: true
      
app:
  order:
    shipping:
      standard-charges: 20
