server:
  port: ${port:8001}

spring:
  application:
    name: user-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

jwt:
  secretkey: TheServerSecretKey

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: $(EUREKA_SERVER:http://localhost:8012/eureka/}
    healthcheck:
      enabled: true

